apiVersion: v1
kind: Pod
metadata:
  name: validator-engine-pod
  labels:
    name: validator-engine-pod
spec:
  volumes:
    - name: validator-engine-pv
      persistentVolumeClaim:
        claimName: validator-engine-pvc
  containers:
    - name: validator-engine-container
      image: ghcr.io/neodix42/ton:latest
      env:
        - name: HOST_IP
          value: "<PUBLIC_IP>"
        - name: PUBLIC_IP
          value: "<PUBLIC_IP>"
        - name: LITESERVER
          value: "true"
      volumeMounts:
        - mountPath: "/var/ton-work/db"
          name: validator-engine-pv
---
kind: Service
apiVersion: v1
metadata:
  name: validator-engine-srv
  annotations:
spec:
  type: LoadBalancer
  loadBalancerIP: <PUBLIC_IP>
  ports:
    - name: validator-engine-udp-port
      nodePort: 30001
      port: 30001
      targetPort: 30001
      protocol: UDP
  selector:
    name: validator-engine-pod
---
kind: Service
apiVersion: v1
metadata:
  name: validator-engine-console-srv
spec:
  type: LoadBalancer
  loadBalancerIP: <PUBLIC_IP>
  ports:
    - name: validator-console-tcp-port
      nodePort: 30002
      port: 30002
      targetPort: 30002
      protocol: TCP
  selector:
    name: validator-engine-pod
---
kind: Service
apiVersion: v1
metadata:
  name: lite-server-srv
spec:
  type: LoadBalancer
  loadBalancerIP: <PUBLIC_IP>
  ports:
    - name: lite-server-tcp-port
      nodePort: 30003
      port: 30003
      targetPort: 30003
      protocol: TCP
  selector:
    name: validator-engine-pod
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: validator-engine-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: <NODE_STORAGE_PATH>
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node_type
              operator: In
              values:
                - ton-validator
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: validator-engine-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
