name: "Nightly brew build"
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, [self-hosted, macOS, ARM64]]
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo "SYSTEM=$(nix eval --raw 'nixpkgs#system')" >> $GITHUB_ENV
        echo "ARCH=$(nix eval --raw 'nixpkgs#hostPlatform.parsed.cpu.name')" >> $GITHUB_ENV
    - uses: cachix/cachix-action@v11
      with:
        name: ton
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .?submodules=1#packages."$SYSTEM".ton-staticbin-dylib --print-build-logs
    - run: |
        nix develop \
          --command bash -e -c '
            mkdir packages-out
            ./packages/brew.sh packages-out $PWD/packages/brew $PWD/result*'
    - if: ${{ !env.ACT }}
      uses: actions/upload-artifact@master
      with:
        name: ton-binaries
        path: result*
    - run: |
        gh release delete -y nightly-brew-"$ARCH"
        gh release create --notes "" nightly-brew-"$ARCH" packages-out/brew-install/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
