name: TON WASM Compile

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Configure & Build
      run: |
        cd assembly/wasm
        chmod +x fift-func-wasm-build-ubuntu.sh
        sudo ./fift-func-wasm-build-ubuntu.sh -a

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-wasm-binaries
        path: artifacts