name: Martyb1666 (shared, x86-64)

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: UQAN_Zkuf16FFRdk2G6cODkJPO-N4VYTE4M2jiFN6nuRMdpf

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build TON
        run: |
          cp assembly/native/build-macos-shared.sh .
          chmod +x build-macos-shared.sh
          ./build-macos-shared.sh -t -a

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ton-binaries-macos-12
          path: artifacts
