name: Docker Compile Ubuntu

on:
  workflow_dispatch:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: test docker buildx
        run: |
          docker buildx version
          docker buildx ls
          pwd
          ls 
          ls github
          docker buildx build --platform=linux/amd64 --progress=plain --load . -t build-18.04-amd64 -f github/script/ubuntu-compile-18.04.Dockerfile
          docker buildx build --platform=linux/arm64 --progress=plain --load . -t build-18.04-arm64 -f github/script/ubuntu-compile-18.04.Dockerfile
          docker buildx build --platform=linux/arm/v7 --progress=plain --load . -t build-18.04-armv7 -f github/script/ubuntu-compile-18.04.Dockerfile
