name: Docker Compile Ubuntu

on:
  workflow_dispatch:
  push:

jobs:
  build:
#    strategy:
#      fail-fast: false
#      matrix:
#        arch: [amd64, arm64]
#        ver: [18.04, 20.04, 22.04]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build with docker buildx
        run: |
          docker buildx version
          docker buildx ls
# docker buildx build --platform=linux/${{matrix.arch}} --progress=plain --load . -t build-${{matrix.ver}}-${{matrix.arch}} -f .github/script/${{matrix.arch}}-${{matrix.ver}}.Dockerfile
          mkdir build-18.04-amd64     
          docker buildx build --platform=linux/amd64 --progress=plain --load . -t build-18.04-amd64 -f .github/script/amd64-18.04.Dockerfile
          container-id=`docker create --platform=linux/amd64 build-18.04-amd64`
          docker cp $container-id:/ton/build/dht-server/dht-server build-18.04-amd64/dht-server

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ton-binaries
          path: build-18.04-amd64

