name: MacOS 11.7 Big Sur x86-64 Compile

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:

    runs-on: macos-11

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build TON
        run: |
          cp assembly/native/build-macos-shared.sh .
          chmod +x build-macos-shared.sh
          ./build-macos-shared.sh -t -a -o 11.7

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ton-macos-11.7
          path: artifacts
