name: MacOS 12.6 Monterey x86-64 Compile

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:

    runs-on: macos-12

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build TON
        run: |
          cp assembly/native/build-macos-shared.sh .
          chmod +x build-macos-shared.sh
          sudo ./build-macos-shared.sh -t -a

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ton-macos-12.6
          path: artifacts
