name: MacOS TON build (portable, x86-64)

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:

    runs-on: macos-11

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build TON
        run: |
          cp assembly/native/build-macos-portable.sh .
          chmod +x build-macos-portable.sh
          ./build-macos-portable.sh -t -a -o 11.7

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ton-binaries-macos-x86-64
          path: artifacts
