name: Ubuntu TON build (portable, x86-64)

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - run: |
        sudo apt update
        sudo apt install -y apt-utils 

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Build TON
      run: |
        cp assembly/nix/linux-x86-64* .
        cp assembly/nix/microhttpd.nix .
        cp assembly/nix/openssl.nix .
        export NIX_PATH=nixpkgs=https://github.com/nixOS/nixpkgs/archive/23.05.tar.gz
        nix-build linux-x86-64-static.nix
        mkdir artifacts
        cp ./result/bin/* artifacts/
        chmod +x artifacts/*
        rm -rf result                             
        nix-build linux-x86-64-tonlib.nix
        cp ./result/lib/libtonlibjson.so.0.5 artifacts/libtonlibjson.so
        cp ./result/lib/libemulator.so artifacts/
        cp -r crypto/fift/lib artifacts/
        cp -r crypto/smartcont artifacts/

    - name: Simple binaries test
      run: |
        sudo mv /nix/store /nix/store2
        artifacts/validator-engine -V
        artifacts/lite-client -V
        artifacts/fift -V
        artifacts/func -V

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-x86_64-linux-binaries
        path: artifacts