name: MacOS TON build (portable, x86-64)

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Build TON
      run: |
        cp assembly/nix/macos-* .
        export NIX_PATH=nixpkgs=https://github.com/nixOS/nixpkgs/archive/23.05.tar.gz
        nix-build macos-static.nix
        mkdir artifacts
        cp ./result-bin/bin/* artifacts/
        chmod +x artifacts/*
        rm -rf result-bin
        nix-build macos-tonlib.nix
        cp ./result/lib/libtonlibjson.dylib artifacts/
        cp ./result/lib/libemulator.dylib artifacts/
        cp -r crypto/fift/lib artifacts/
        cp -r crypto/smartcont artifacts/

    - name: Simple binaries test
      run: |
        sudo mv /nix/store /nix/store2
        artifacts/validator-engine -V
        artifacts/lite-client -V
        artifacts/fift -V
        artifacts/func -V

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-x86_64-macos-binaries
        path: artifacts