name: "TON x86_64 macOS build"

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: macos-12
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

#    - uses: cachix/cachix-action@v11
#      with:
#        name: ton
#        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Compile
      run: nix build .?submodules=1#packages.x86_64-darwin.ton-staticbin-dylib --print-build-logs -o result-x86_64-darwin

    - name: Copy binaries
      run: |
        mkdir artifacts
        cp  $PWD/result-x86_64-darwin-bin/* artifacts/
        cp -R crypto/smartcont artifacts/
        cp -R crypto/fift/lib artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-x86_64-macos-binaries
        path: artifacts
