name: Tonlib Android JNI

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:      
        submodules: 'recursive'

    - name: Build TON
      run: |
        cp assembly/android/build-android-tonlib.sh .
        chmod +x build-android-tonlib.sh
        sudo -E ./build-android-tonlib.sh -a

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: tonlib-android-jni
        path: artifacts