name: Ubuntu TON build

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:      
        submodules: 'recursive'

    - name: Build TON
      run: |
        cp assembly/native/build-ubuntu-20.04-shared.sh .
        chmod +x build-ubuntu-20.04-shared.sh
        sudo ./build-ubuntu-20.04-shared.sh -t -a

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-binaries-${{ matrix.os }}
        path: artifacts
