name: Ubuntu TON build (portable, x86-64)

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:      
        submodules: 'recursive'

    - name: Install system libraries
      run: |
        sudo apt-get update
        sudo apt remove -y libsecp256k1-dev libmicrohttpd-dev libsodium-dev libgsl-dev libblas-dev libreadline-dev
        sudo apt-get install -y build-essential git cmake ninja-build automake libtool texinfo autoconf

    - name: Build TON
      run: |
        cp assembly/native/build-ubuntu-20.04-portable.sh .
        chmod +x build-ubuntu-20.04-portable.sh
        sudo ./build-ubuntu-20.04-portable.sh -t -a

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-binaries-linux-x86-64
        path: artifacts
